import json
import re
import threading
from sqlalchemy.orm import Session
from database import SessionLocal
from models import Article, Tag
from ollama_client import chat

SYSTEM_SUMMARISE = (
    "You are a technical assistant. Summarise the article in 3-4 sentences, "
    "then extract 3-5 relevant tags as a JSON list. "
    "Reply with JSON: {\"summary\": \"...\", \"tags\": [\"tag1\", ...]}"
)

# Lock only for the atomic claim step (held for milliseconds, not during LLM calls)
_claim_lock = threading.Lock()

def enrich_article(article: Article, db: Session) -> None:
    text = (article.content or article.title)[:2000]

    try:
        raw = chat(text, system=SYSTEM_SUMMARISE)
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        data = json.loads(match.group()) if match else {}
        article.summary = data.get("summary") or raw[:500]
        tag_names = data.get("tags", [])
    except Exception:
        article.summary = (article.content or "")[:300]
        tag_names = []

    for name in tag_names[:5]:
        name = name.strip().lower()
        if not name:
            continue
        tag = db.query(Tag).filter(Tag.name == name).first()
        if not tag:
            tag = Tag(name=name)
            db.add(tag)
            db.flush()
        if tag not in article.tags:
            article.tags.append(tag)

    # Embedding is generated by embed_missing worker (nomic runs separately,
    # no competition with qwen3 slots used here for chat)
    article.status = "enrichi"
    db.commit()


def run_enricher(batch: int = 25) -> int:
    """
    Claim a batch of articles atomically (collecte → processing),
    then enrich each one. The claim step uses a threading lock held
    for milliseconds only — the slow LLM calls happen outside the lock.
    """
    # ── Step 1: claim articles atomically ──────────────────────────────
    db = SessionLocal()
    article_ids: list[int] = []
    try:
        with _claim_lock:
            rows = (
                db.query(Article.id)
                .filter(Article.status == "collecte")
                .limit(batch)
                .all()
            )
            article_ids = [r[0] for r in rows]
            if article_ids:
                db.query(Article).filter(Article.id.in_(article_ids)).update(
                    {"status": "processing"}, synchronize_session=False
                )
                db.commit()
    except Exception:
        db.rollback()
        article_ids = []
    finally:
        db.close()

    if not article_ids:
        return 0

    # ── Step 2: enrich each claimed article (slow LLM calls, no lock) ──
    from pipeline_stats import stats as _stats
    count = 0
    db = SessionLocal()
    try:
        for article_id in article_ids:
            article = db.get(Article, article_id)
            if not article:
                continue
            try:
                enrich_article(article, db)
                count += 1
                _stats.record_enriched()
            except Exception:
                db.rollback()
                _stats.record_enrich_error()
                # On failure: revert to collecte so it gets retried
                try:
                    a = db.get(Article, article_id)
                    if a and a.status == "processing":
                        a.status = "collecte"
                        db.commit()
                except Exception:
                    db.rollback()
    finally:
        db.close()

    return count
